### ISSUE TITLE
Block sync randomly stops since upgrading to 2.7.2

### ISSUE THREAD

**Issue by pstroinski** [OpenEthereum/open-ethereum#11539] opened 2020-03-03 21:14 UTC
- **Parity Ethereum version**: 2.7.2
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

After upgrading nodes to version 2.7.2 observing the same behavior on all of them. Randomly node stops syncing blocks. There is no error, node just stops on some block and nothing more is logged. After restart nodes starts syncing again. 
Observed already on 4 nodes on different dates and times.

Logs from now:
2020-02-29 08:40:59 UTC   23/25 peers      6 MiB chain  102 MiB db  0 bytes queue   81 MiB sync  RPC:  0 conn,    4 req/s,                                                                    234 µs
2020-02-29 08:41:33 UTC   23/25 peers      6 MiB chain  102 MiB db  0 bytes queue   81 MiB sync  RPC:  0 conn,    4 req/s,                                                                    189 µs
2020-02-29 08:42:01 UTC Imported #9577611 0x462d…6c7f (209 txs, 9.97 Mgas, 1638 ms, 38.78 KiB)
2020-02-29 08:42:03 UTC   23/25 peers      6 MiB chain  102 MiB db  0 bytes queue   81 MiB sync  RPC:  0 conn,    4 req/s,                                                                    195 µs
2020-02-29 08:42:06 UTC Imported #9577613 0x25c7…54e6 (64 txs, 4.31 Mgas, 1292 ms, 14.29 KiB)

Here is the restart:
2020-03-03 21:04:19 UTC Finishing work, please wait...
2020-03-03 21:07:14 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-03 21:07:14 UTC Keys path /var/parity/keys/ethereum
2020-03-03 21:07:14 UTC DB path /var/parity/chains/ethereum/db/906a34e69aec8c0d
2020-03-03 21:07:14 UTC State DB configuration: fast
2020-03-03 21:07:14 UTC Operating mode: active
2020-03-03 21:07:34 UTC Configured for Ethereum using Ethash engine
2020-03-03 21:07:35 UTC Running without a persistent transaction queue.
2020-03-03 21:07:35 UTC Removed existing file '/var/parity/jsonrpc.ipc'.
2020-03-03 21:07:36 UTC Updated conversion rate to Ξ1 = US$222.50 (21401816 wei/gas)
2020-03-03 21:07:41 UTC Public node URL: enode://78ea5864854c598577812b93bbc861a49537ec3bbaa0041d5b300472fd8923fbf31fcb65e4                                                                  c592eb0ecda909a00e5c8110d31bfbe4ee126d10fd99e46036b438@172.18.0.2:30303
2020-03-03 21:07:55 UTC Syncing #9577614 0x41a0…af1f     0.05 blk/s    0.6 tx/s    0.5 Mgas/s    162+  203 Qed  #9577994                                                                      6/25 peers     89 KiB chain   82 MiB db   31 MiB queue  643 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2020-03-03 21:08:01 UTC Syncing #9577617 0xa8b1…bedc     0.60 blk/s   79.0 tx/s    4.8 Mgas/s      0+  368 Qed  #9577994

**Comment by dvdplm** [comment] 2020-03-04 07:03
Duplicate of https://github.com/OpenEthereum/open-ethereum/issues/11494

**Closed by dvdplm** 2020-03-04 07:03 UTC
