### ISSUE TITLE
Thread 'IO Worker #3' panicked

### ISSUE THREAD

**Issue by zemse** [OpenEthereum/open-ethereum#11535] opened 2020-03-03 11:21 UTC
Reporting because got an error which said to report it here:
```
                       at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/mod.rs:470
  23:     0x55bf638d6ac2 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heb2c44a48c82a203
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:315
  24:     0x55bf638dbcca - std::panicking::try::do_call::h99615ddd8e833f5e
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
  25:     0x55bf65460c29 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:80
  26:     0x55bf638db95f - std::panicking::try::h196a53732a33b650
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  27:     0x55bf638d6b52 - std::panic::catch_unwind::h5a4c56c6771470c4
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
  28:     0x55bf638cb599 - std::thread::Builder::spawn_unchecked::{{closure}}::hb81b5e5e2ac9dd06
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/mod.rs:469
  29:     0x55bf63864c93 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha87059353af43ee0
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
  30:     0x55bf654422ce - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  31:     0x55bf6545ff6f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
                         - std::sys_common::thread::start_thread::h557b0c2dc4449562
                        at src/libstd/sys_common/thread.rs:13
                         - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
                        at src/libstd/sys/unix/thread.rs:79
  32:     0x7fc0abe7c6da - start_thread
  33:     0x7fc0ab58188e - __clone
  34:                0x0 - <unknown>

Thread 'IO Worker #3' panicked at 'proof produced by this engine; therefore it is valid; qed', src/libcore/option.rs:1190

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


Aborted (core dumped)
```

- **Parity Ethereum version**: 2.7.0
- **Operating system**: Linux
- **Installation**:  built from source
- **Fully synchronized**: yes
- **Network**: PoA private
- **Restarted**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by niklasad1** [comment] 2020-03-03 11:41
@zemse 

Can you please share your chain configuration? It is very hard to produce without it

**Comment by niklasad1** [comment] 2020-03-03 11:45
Duplicate of #11511, closing.

**Closed by niklasad1** 2020-03-03 11:45 UTC
